### ISSUE TITLE
rcdkjar fails to compile with CDK nightly, missing IsotopeFactory

### ISSUE THREAD

**Issue by sneumann** [rajarshi/cdkr#18]
Hi, I am trying to compile with an updated cdk.jar.
While it works with the included cdk-1.5.2, it does not work 
with the download of cdk-1.5.5.ar from sf.net nor the nightly.
This is with javac 1.7.0_51 on Linux.

```
    [javac] /vol/R/rguha/cdkr/rcdkjar/src/org/guha/rcdk/util/Misc.java:188: error: cannot find symbol
    [javac]             IsotopeFactory ifac = IsotopeFactory.getInstance(DefaultChemObjectBuilder.getInstance());
```
